spring:
  batch:
    job:
      enabled: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        validation-query: select 1
        validation-query-timeout: 2000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/springbatch?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: 123456
        slave1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/springbatch1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: 123456
        slave2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/springbatch2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
          username: root
          password: 123456

  shardingsphere:
    mode:
      type: Memory
    props:
      sql-show: true
    datasource:
      names: ds0,ds1,ds2
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/store_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/product_db_1?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/product_db_2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 123456

    rules:
      sharding:
        tables:
          t_region:
            actual-data-nodes: ds$->{0..2}.t_region
          t_store_info:
            actual-data-nodes: ds$->{0}.t_store_info
          t_product_info:
            actual-data-nodes: ds$->{1..2}.t_product_info_$->{1..2}
            key-generate-strategy:
              column: product_info_id
              key-generator-name: leaf-segment1
            database-strategy:
              standard:
                sharding-column: store_info_id
                sharding-algorithm-name: database-product-info-inline
            table-strategy:
              standard:
                sharding-column: product_info_id
                sharding-algorithm-name: table-product-info-inline
          t_product_descript:
            actual-data-nodes: ds$->{1..2}.t_product_descript_$->{1..2}
            key-generate-strategy:
              column: id
              key-generator-name: leaf-segment2
            database-strategy:
              standard:
                sharding-column: store_info_id
                sharding-algorithm-name: database-product-descript-inline
            table-strategy:
              standard:
                sharding-column: product_info_id
                sharding-algorithm-name: table-product-descript-inline

        sharding-algorithms:
          database-product-info-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{store_info_id % 2 + 1}
          database-product-descript-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{store_info_id % 2 + 1}
          table-product-info-inline:
            type: INLINE
            props:
              algorithm-expression: t_product_info_$->{product_info_id % 2 + 1}
          table-product-descript-inline:
            type: INLINE
            props:
              algorithm-expression: t_product_descript_$->{product_info_id % 2 + 1}
        key-generators:
          snowflake:
            type: SNOWFLAKE
          leaf-segment1:
            type: leafSegment
            props:
              biz-tag: leaf-segment-test
          leaf-segment2:
            type: leafSegment
            props:
              biz-tag: leaf-segment-test2
          leaf-snowflake:
            type: leafSnowflake

        broadcast-tables:
          - t_region
        binding-tables:
          - t_product_info,t_product_descript